pipeline:

  test:
    image: node:10
    commands:
      - npm ci
      - npm test
    when:
      event:
        - push
        - tag
        - pull_request

  audit:
    image: node:10
    commands:
      - npx @lennym/ciaudit
    when:
      event:
        - push
        - tag
        - pull_request

  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t asl-stub .
    when:
      branch: master
      event:
        - push
        - pull_request

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-stub quay.io/ukhomeofficedigital/asl-stub:latest
      - docker push quay.io/ukhomeofficedigital/asl-stub:latest
    when:
      branch: master
      event: push

  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t asl-stub .
    when:
      event: tag

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-stub quay.io/ukhomeofficedigital/asl-stub:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/asl-stub:$${DRONE_TAG}
    when:
      event: tag
