
kind: pipeline
name: default
type: kubernetes
steps:
  - name: install
    image: node:12
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm ci
  - name: test
    image: node:12
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm test
  - name: audit
    image: node:12
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npx @lennym/ciaudit --retries 5
  - name: docker build
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - docker build --build-arg NPM_AUTH_USERNAME=$${NPM_AUTH_USERNAME} --build-arg NPM_AUTH_TOKEN=$${NPM_AUTH_TOKEN} -t asl-stub .
  - name: docker push
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-stub quay.io/ukhomeofficedigital/asl-stub:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl-stub:$${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

services:
- name: docker
  image: docker:dind
  environment:
    DOCKER_TLS_CERTDIR: ""
- name: postgres
  image: postgres
  environment:
    POSTGRES_USER: asl-test
    POSTGRES_PASSWORD: test-password
